### ISSUE TITLE
presignedPostPolicy Content-Type checking

### ISSUE THREAD

**Issue by kirick1** [minio/minio-js#782] opened 2019-07-22 05:52 UTC
I am trying to upload files to my bucket using this method:
```
async generatePresignedPostPolicy (storeId, { expiry = 24*60*60, contentType, minLength = 1024, maxLength = 10*1024*1024 }) {
    try {
      const policy = this.getClient().newPostPolicy();
      policy.setBucket(this.bucket);
      policy.setKeyStartsWith(`${storeId}/uploads`);

      const expires = new Date();
      expires.setSeconds(expiry);
      policy.setExpires(expires);

      policy.setContentType(contentType);
      policy.setContentLengthRange(minLength, maxLength);

      console.log('POLICY', inspect(policy, { depth: 5 }));

      return await this.getClient().presignedPostPolicy(policy);
    } catch (error) {
      console.error('ERROR GENERATING PRESIGNED POST POLICY: ', error)
      throw new SystemError(error);
    }
  }
```
Created policy object in console:
```
POLICY PostPolicy {
    policy:
        { conditions:
            [ [ 'eq', '$bucket', 'stage-users-blogs' ],
              [ 'starts-with',
                '$key',
                '38b452b3-53ee-40dc-81ba-08a2ceff4cb9/uploads' ],
              [ 'eq', '$Content-Type', 'image/png' ],
              [ 'content-length-range', 1024, 1048576 ] ],
          expiration: '2019-07-23T05:34:00.065Z' },
    formData:
        { bucket: 'stage-users-blogs',
          key: '38b452b3-53ee-40dc-81ba-08a2ceff4cb9/uploads',
          'Content-Type': 'image/png' } }
```
Created post policy object:
```
{
    "postURL": "http://localhost:9000/stage-users-blogs",
    "formData": {
        "bucket": "stage-users-blogs",
        "key": "38b452b3-53ee-40dc-81ba-08a2ceff4cb9/uploads",
        "Content-Type": "image/png",
        "x-amz-date": "20190722T053406Z",
        "x-amz-algorithm": "AWS4-HMAC-SHA256",
        "x-amz-credential": "9480610E5E844F7E7A6C/20190722/us-east-1/s3/aws4_request",
        "policy": "eyJjb25kaXRpb25zIjpbWyJlcSIsIiRidWNrZXQiLCJzdGFnZS11c2Vycy1ibG9ncyJdLFsic3RhcnRzLXdpdGgiLCIka2V5IiwiMzhiNDUyYjMtNTNlZS00MGRjLTgxYmEtMDhhMmNlZmY0Y2I5L3VwbG9hZHMiXSxbImVxIiwiJENvbnRlbnQtVHlwZSIsImltYWdlL3BuZyJdLFsiY29udGVudC1sZW5ndGgtcmFuZ2UiLDEwMjQsMTA0ODU3Nl0sWyJlcSIsIiR4LWFtei1kYXRlIiwiMjAxOTA3MjJUMDUzNDA2WiJdLFsiZXEiLCIkeC1hbXotYWxnb3JpdGhtIiwiQVdTNC1ITUFDLVNIQTI1NiJdLFsiZXEiLCIkeC1hbXotY3JlZGVudGlhbCIsIjk0ODA2MTBFNUU4NDRGN0U3QTZDLzIwMTkwNzIyL3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QiXV0sImV4cGlyYXRpb24iOiIyMDE5LTA3LTIzVDA1OjM0OjAwLjA2NVoifQ==",
        "x-amz-signature": "83523b486ebc18dc6b20c6cfda96c78cb1d9cb25448cb1891e6d939540f55cf0"
    }
}
```
But when I try to upload any file with content-type, for example _text/csv_ with key `012345678/image.jpg` Minio server responses me with status 204 and everything upload's good without any checking for file content-type and key start's with. How can I add exactly checking for  uploaded file content-type? another flags, for example content-length-range and expiration are working correctly.

**Comment by kannappanr** [comment] 2019-07-22 13:45
@kirick1 Thanks for filing this issue. This issue is a duplicate of https://github.com/minio/minio/issues/7806 I believe the fix for that issue will fix this one. Please monitor the referenced issue

**Comment by kannappanr** [comment] 2019-07-26 20:58
@kirick1 closing this issue as duplicate of minio/minio#7806 Please follow the progess of the PR https://github.com/minio/minio/pull/7937 . closing this issue now. Please feel free to let us know if you feel otherwise.

**Closed by kannappanr** 2019-07-26 20:58 UTC
Labels: community, priority: medium
