### ISSUE TITLE
copyObject NoSuchBucket error 

### ISSUE THREAD

**Issue by BarthaBRW** [minio/minio-js#840] opened 2020-03-24 16:43 UTC
Hi there,
Uploading and removing a file works well as expected, but I get **NoSuchBucket** error when trying to copy a file. 

Versions:

- node v12.13.0
- minio client v7.0.15
- minio server version RELEASE.2020-03-19T21-49-00Z

```
const minio = new Minio.Client({
	endPoint: "...",
	accessKey: "...",
	secretKey: "..."
});
```
```
minio.putObject("bucket-name", "targetfile", "value", err => {
	// OK
});
```
```
minio.removeObject("bucket-name", "targetfile", err => {
	// OK
});
```
```
minio.copyObject("bucket-name", "targetfile", "sourcefile", err => {
	// Error, see below
});
```

```
{
  code: 'NoSuchBucket',
  key: 'targetfile',
  bucketname: 'bucket-name',
  resource: '/bucket-name/targetfile',
  requestid: '15FF49B16917F4FE',
  hostid: '21a4be56-eb97-4b8a-9b6e-9048b6fbc8c0',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}

```
Also tried passing a new Minio.CopyConditions to the copyObject following the documentation and switching sourcefile and targetfile parameters but with the same result.
Any suggestion?

**Comment by kannappanr** [comment] 2020-03-24 19:29
@BarthaBRW Tried the following code against play

```
var Minio = require('minio')

var s3Client = new Minio.Client({
  endPoint: 'play.min.io',
  accessKey: 'minio',
  secretKey: 'minio123',
  port: 9000,
  useSSL: true
}) 

var conds = new Minio.CopyConditions()

s3Client.copyObject('test', 'destination', '/test/source', conds, function(e, data) {
  if (e) {
    return console.log(e)
  }
  console.log("Successfully copied the object:")
  console.log("etag = " + data.etag + ", lastModified = " + data.lastModified)
})
```
I was unable to reproduce the issue with the same version of `minio-js`

**Comment by BarthaBRW** [comment] 2020-03-24 19:48
Thanks your quick reply. Your code looks to be working, so at the moment I am not sure what can go wrong.

**Comment by kannappanr** [comment] 2020-03-28 22:18
@BarthaBRW Not sure how we can help here. I have not really come across anything like this. You can add tracing on both client side and server side and see if you can find any clue there. Closing this issue now. Please feel free to attach any logs that might be helpful for us to look at.

**Closed by kannappanr** 2020-03-28 22:18 UTC

**Comment by capan** [comment] 2021-03-17 21:35
Having the same problem here

**Comment by Pierre-Green** [comment] 2021-06-03 17:59
You have to prefix the source file with its bucket

`await s3Client.copyObject(bucket, 'newFile', bucket + '/oldFile', conds)`
