### ISSUE TITLE
make sure that key is a string before doing a toLowerCase

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio-js#554] opened 2017-02-27 15:52 UTC
`TypeError: key.toLowerCase is not a function`

https://github.com/minio/minio-js/blob/eacc4adc37d77b7ad17b989a10cb985554203372/src/main/xml-parsers.js#L56

**Comment by krishnasrinivas** [comment] 2017-03-13 05:29
@dcharbonnier do you know how to reproduce the error? I am wondering how the key can be non-string. Maybe there was an nginx proxy that returned gateway-error (which would not have XML?)

**Comment by harshavardhana** [comment] 2017-03-13 05:59
> @dcharbonnier do you know how to reproduce the error? I am wondering how the key can be non-string. Maybe there was an nginx proxy that returned gateway-error (which would not have XML?)

Most probably because of nginx timeout where it would have returned HTML body.

**Comment by dcharbonnier** [comment] 2017-03-13 08:10
the question of how we get there does not seams very important, you assume that the response is always html but maybe there is a proxy, or maybe at some point the server I'm talking to will have a bug.
I don't expect the client to crash because the server does not return what I think it should, I expect an error telling me the library is not able to understand the reply.

**Comment by harshavardhana** [comment] 2017-03-13 15:31
> the question of how we get there does not seams very important, you assume that the response is always html but maybe there is a proxy, or maybe at some point the server I'm talking to will have a bug.
> I don't expect the client to crash because the server does not return what I think it should, I expect an error telling me the library is not able to understand the reply.

:+1: agreed.

**Comment by krishnasrinivas** [comment] 2017-03-13 16:28
> the question of how we get there does not seams very important, you assume that the response is always html but maybe there is a proxy, or maybe at some point the server I'm talking to will have a bug.
> I don't expect the client to crash because the server does not return what I think it should, I expect an error telling me the library is not able to understand the reply.

Ofcourse the library needs fix, my question was just for our understanding of the setup/context.

**Comment by krishnasrinivas** [comment] 2017-03-13 16:33
This bug was fixed in 6e5913a30eece960b5f3af6da22a6b4ba6f2ec01 and available in the latest release 3.1.2

**Closed** 2017-03-13 16:36 UTC

**Comment by dcharbonnier** [comment] 2017-03-13 17:15
Sorry I don't remember exactly the context but maybe a caddy proxy or a ssl
setup problem (not sure this one can create this problem).
