### ISSUE TITLE
The querystring API is considered Legacy

### ISSUE THREAD

**Issue by bttger** [minio/minio-js#1010] opened 2022-03-28 17:49 UTC
Just got a message from npm that the querystring API is considered legacy. The minio JS client relies on it.

```
This package has been deprecated
Author message:

The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```
https://www.npmjs.com/package/querystring

**Comment by prakashsvmx** [comment] 2022-04-04 04:59
@bttger We will upgrade soon. Thank you

**Comment by prakashsvmx** [comment] 2022-04-04 05:22
Duplicate of #1003

**Closed by prakashsvmx** 2022-04-04 05:22 UTC

**Comment by moisesbites** [comment] 2022-07-27 23:18
Up
