### ISSUE TITLE
Support for proxies?

### ISSUE THREAD

**Issue by frederickjansen** [minio/minio-js#598] opened 2017-06-13 19:48 UTC
Is there any way to instruct Minio to connect to the endPoint using a proxy? I can't see a way to pass in a proxy config. I thought it would be possible to use a library such as [global-tunnel](https://github.com/np-maintain/global-tunnel), which monkey-patches http.agent, but Minio sets its own agent to support keep-alive and overwrites global-tunnel.

**Comment by krishnasrinivas** [comment] 2017-06-13 21:36
Looks like aws sdk supports it http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html

**Comment by frederickjansen** [comment] 2017-06-13 21:42
Hi Krishna

Are you suggesting I use the AWS SDK instead of Minio? I'm using Minio for other purposes, so that wouldn't be an option in my case.

**Comment by krishnasrinivas** [comment] 2017-06-13 23:10
@frederickjansen no, sorry, that message was for other minio developers saying that we can implement it as well.

**Comment by deekoder** [comment] 2017-09-19 22:02
@frederickjansen we will look into this in a subsequent release. Moving this item to future milestone.

**Comment by harshavardhana** [comment] 2017-09-19 22:30
For the time being you have a work-around btw - @frederickjansen 

```js
var proxy = require('proxy-agent');
var Minio = require('minio');
var s3Client = new Minio.Client({
  endPoint: 's3.amazonaws.com',
  accessKey: 'YOUR-ACCESSKEYID',
  secretKey: 'YOUR-SECRETACCESSKEY'
})

s3Client.agent = proxy('http://internal.proxy.com')
```

**Comment by deekoder** [comment] 2018-02-06 22:46
This workaround should help. So closing this as a won't fix. Please reactivate if you want to discuss this further.

**Closed by deekoder** 2018-02-06 22:46 UTC
Labels: priority: medium, wontfix

**Comment by sonyz** [comment] 2020-02-19 07:15
Hi,
The workaround is not working
The env variables HTTP_PROXY and HTTPS_PROXY is not used.

**Comment by harshavardhana** [comment] 2020-02-19 07:29
> s3Client.agent = proxy('http://internal.proxy.com')

The work around is to use this @sonyz

**Comment by shanewholloway** [comment] 2020-05-20 14:52
Confirmed working with [mitmproxy.org](https://mitmproxy.org/)

```javascript
// my test_client.js
const Minio = require('minio')
const proxy_agent = require('proxy-agent')

const s3Client = new Minio.Client({
    endPoint: 'minio', port: 9000, useSSL: false,
    accessKey: accessKeyId, secretKey: secretAccessKey })

if (process.env.http_proxy) {
  s3Client.setRequestOptions({
    agent: proxy_agent(process.env.http_proxy)
  })
}
```

```dockerfile
# Dockerfile
ENV http_proxy=http://mitmproxy:8080
```
