### ISSUE TITLE
putObject callback should return lastModified like copyObject

### ISSUE THREAD

**Issue by guoyibj** [minio/minio-js#856] opened 2020-06-28 03:37 UTC

**Comment by ebozduman** [comment] 2020-07-15 11:24
@guoyibj,

MinIO is s3 compatible. That's why we cannot change `putObject` behavior and return `LastModified` information like `copyObject`.

Our implementation is correct, so marking the issue as `working as intended`.

Please let us know if you disagree. If not, please close the issue.

**Comment by kannappanr** [comment] 2020-07-15 18:24
Here is the response syntax for copyobject
```
HTTP/1.1 200
x-amz-expiration: Expiration
x-amz-copy-source-version-id: CopySourceVersionId
x-amz-version-id: VersionId
x-amz-server-side-encryption: ServerSideEncryption
x-amz-server-side-encryption-customer-algorithm: SSECustomerAlgorithm
x-amz-server-side-encryption-customer-key-MD5: SSECustomerKeyMD5
x-amz-server-side-encryption-aws-kms-key-id: SSEKMSKeyId
x-amz-server-side-encryption-context: SSEKMSEncryptionContext
x-amz-request-charged: RequestCharged
<?xml version="1.0" encoding="UTF-8"?>
<CopyObjectResult>
   <ETag>string</ETag>
   <LastModified>timestamp</LastModified>
</CopyObjectResult>
```

Here is the response syntax for PutObject call

```
HTTP/1.1 200
x-amz-expiration: Expiration
ETag: ETag
x-amz-server-side-encryption: ServerSideEncryption
x-amz-version-id: VersionId
x-amz-server-side-encryption-customer-algorithm: SSECustomerAlgorithm
x-amz-server-side-encryption-customer-key-MD5: SSECustomerKeyMD5
x-amz-server-side-encryption-aws-kms-key-id: SSEKMSKeyId
x-amz-server-side-encryption-context: SSEKMSEncryptionContext
x-amz-request-charged: RequestCharged
```
As explained by @ebozduman Closing this issue as working as intended.

**Closed by kannappanr** 2020-07-15 18:24 UTC
Labels: community, priority: medium, working as intended
