### ISSUE TITLE
Extend putObject API to accept user metadata for the object

### ISSUE THREAD

**Issue by kishoresanke** [minio/minio-js#615] opened 2017-08-11 09:57 UTC
Extend putObject API to accept user metadata for the object

**Comment by harshavardhana** [comment] 2017-08-25 03:02
Thanks @kishoresanke we will be fixing this soon.

**Comment by harshavardhana** [comment] 2017-08-25 06:15
This requires an API change to be implemented along the same lines as minio-go API in this regard https://github.com/minio/minio-go/issues/747

**Comment by ebozduman** [comment] 2017-08-30 22:52
We need to finish the on-going minio-go put object refactoring effort before resolving this issue. 
#747

**Comment by deekoder** [comment] 2017-09-06 01:02
We will do it in the future milestone. We are already on our way to having this in minio-go

**Comment by harshavardhana** [comment] 2018-01-04 22:47
Unblocking since minio/minio-go#747 is accepted and released.

**Comment by deekoder** [comment] 2018-02-06 22:49
Duplicate of #555

**Comment by deekoder** [comment] 2018-02-06 22:49
Closing this issue here. @kishoresanke  please follow #555 for this request.

**Closed by deekoder** 2018-02-06 22:49 UTC
Labels: duplicate, priority: medium
