### ISSUE TITLE
Docs updated but package is behind on the api

### ISSUE THREAD

**Issue by YvanDaSilva** [minio/minio-js#680] opened 2018-03-24 23:55 UTC
Hello,

## Concerns

version : minio-js v4.0.0
documentation : https://docs.minio.io/docs/javascript-client-api-reference#bucketExists
commit :  https://github.com/minio/minio-js/commit/ccd2c236e65609c2d0f847f93fcef0c3d56ed34d

## Function
"bucketExists"

## Notes
The documentation reflects the very last change in the API, however the package available on npm doesn't have those changes.

## Problem

Documentation says bucketExists receives a callback with two values (err, exists). Exists being a boolean.

## Expected
The package reflects the documentation (or the other way around).

##  Current result
The package still accepts only a callback with "err" only.

**Comment by harshavardhana** [comment] 2018-03-24 23:56
This change is in master and not released yet @YvanDaSilva we will make a release soon.

**Comment by YvanDaSilva** [comment] 2018-03-24 23:57
@harshavardhana Yes, I know. However the documentation reflects master then ? 
Should the documentation correspond to a tagged version =

**Comment by harshavardhana** [comment] 2018-03-25 00:03
> @harshavardhana Yes, I know. However the documentation reflects master then ?
> Shouldn't the documentation correspond to a tagged version ?

The problem is due to API.md is directly used to update docs.minio.io so any change in master gets reflected. So API.md doc points to latest master not latest release, release sometimes can get a couple of days behind when we make breaking change but we will soon make a new release.

**Comment by YvanDaSilva** [comment] 2018-03-25 00:16
@harshavardhana Do you want me to open a new feature request for the docs so you have the possibility to select the docs for a specific version ?
It would be nice to have a version selection, example : https://lodash.com/docs

**Comment by harshavardhana** [comment] 2018-03-25 00:18
> @harshavardhana Do you want me to open a new feature request for the docs so you have the possibility to select the docs for a specific version ?
> It would be nice to have a version selection, example : https://lodash.com/docs

We are working on that in minio/gluegun which is the replacement for that to minio/doctor .

**Comment by harshavardhana** [comment] 2018-03-25 00:51
This is fixed released 5.0.0 - closing.

**Closed by harshavardhana** 2018-03-25 00:51 UTC
