### ISSUE TITLE
listObjects will stop responding when no objects in a bucket

### ISSUE THREAD

**Issue by manjeshpv** [minio/minio-js#521] opened 2016-11-26 14:58 UTC
In the below code, Both callback wont works when no objects inside bucket `resolve` and `reject`

```js
var objectsStream = minio.listObjects(req.query.name, '', false)
objectsStream.on('data',  resolve)
objectsStream.on('end',  reject)
```

```sh
(node:3180) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'code' of undefined
```

**Comment by vadmeste** [comment] 2016-11-26 15:50
@manjeshpv, I am not able to reproduce this bug, can you show a more complete example ?

By the way, notice that your reject() will receive 'undefined' when there is no entries in your bucket.

**Comment by harshavardhana** [comment] 2016-12-09 08:27
Closing this as not a bug, @manjeshpv if you think we need to address this on our end.

**Closed by harshavardhana** 2016-12-09 08:27 UTC
