### ISSUE TITLE
InvalidEndpointError: Invalid endPoint : undefined

### ISSUE THREAD

**Issue by fordtn** [minio/minio-js#871] opened 2020-11-13 08:29 UTC
Any idea how to fix this ?

aristoslabs@Alabs-II common_service % npm start

> pracman_backend@1.0.0 start /Users/aristoslabs/ITW/common_service
> node build/index.js

/Users/aristoslabs/ITW/common_service/node_modules/minio/dist/main/minio.js:90
      throw new errors.InvalidEndpointError(`Invalid endPoint : ${params.endPoint}`);
      ^
InvalidEndpointError: Invalid endPoint : undefined
    at new Client (/Users/aristoslabs/ITW/common_service/node_modules/minio/dist/main/minio.js:90:13)
    at Object.<anonymous> (/Users/aristoslabs/ITW/common_service/build/api/middlewares/ExoScaleUpload.js:8:21)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/Users/aristoslabs/ITW/common_service/build/config/routes.js:44:26)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/Users/aristoslabs/ITW/common_service/build/app.js:24:18)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/Users/aristoslabs/ITW/common_service/build/index.js:31:15)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pracman_backend@1.0.0 start: `node build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pracman_backend@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aristoslabs/.npm/_logs/2020-11-13T07_22_58_486Z-debug.log

**Comment by ebozduman** [comment] 2020-12-04 10:51
@fordtn ,

It looks like, when you `npm start`, your script tries to create an instance of the MinIO server you are running at an endPoint` with credentials `accessKey` and `secretKey` in your environment.

This is defined in your script, similar to the below line of code:
```
var minioClient = new Minio.Client({
  endPoint: 'your.min.io',
  accessKey: 'YOUR-ACCESSKEYID',
  secretKey: 'YOUR-SECRETACCESSKEY'
})

```

We validate the provided `endPoint` and make sure it is a valid point. If not, then the error you see is thrown.

Please make sure your definition of `endPoint` is correct and matches the MinIO server you are running in your setup. Also make sure you can reach the server at your `endPoint` with your credentials.

Let me know if this is a simple typo or wrong name in your `endPoint`. 
If that is the case, then please close this issue.

Otherwise, you need to tell us how you started your MinIO server and how you create your `minioClient` etc.

**Comment by ebozduman** [comment] 2021-01-08 00:31
As we did not hear anything about if this is a user error or the reproduction steps if the issue is legit.

So, closing it as `working as intended`.

**Closed by ebozduman** 2021-01-08 00:31 UTC
Labels: community, working as intended
