### ISSUE TITLE
There was an error when I was installing the MINIO package. I do not know where the error occurred

### ISSUE THREAD

**Issue by 1589101207** [minio/minio-js#1064] opened 2022-09-02 02:14 UTC
![image](https://user-images.githubusercontent.com/72295903/188043481-d1db4987-149b-45b0-ba8c-a4820a60a556.png)
![image](https://user-images.githubusercontent.com/72295903/188044196-2a218237-5484-4d5a-92f1-e095142f65ef.png)

There was an error when I was installing the MINIO package. I do not know where the error occurred，The project configuration is Vue2+elment- UI + Axios, scaffolding is VUUE - CLI is 3.

**Comment by prakashsvmx** [comment] 2022-09-02 03:03
Duplicate of #1063 

For a possible solution: Please refer to https://github.com/minio/minio-js/issues/1063#issuecomment-1234544020

**Closed by prakashsvmx** 2022-09-02 03:03 UTC
