### ISSUE TITLE
Not find a way to set timeout for http/https request

### ISSUE THREAD

**Issue by AlloVince** [minio/minio-js#722] opened 2018-10-07 09:10 UTC
I found that minio use node.js http/https module to send request, however currently there is not a timeout handler for every request, if network not stable, unfinished http request will not release.

Please consider add timeout option for request in `makeRequest()` method such as
https://github.com/minio/minio-js/blob/master/src/main/minio.js#L399

```
req.setTimeout(1000, function() {                                                                                                                              
    req.abort();                                                                                                                                               
});
```

**Comment by harshavardhana** [comment] 2018-10-07 09:29
@AlloVince can you not do 

https://docs.minio.io/docs/javascript-client-api-reference.html

> 6. HTTP request options
> setRequestOptions(options)
> Set the HTTP/HTTPS request options. Supported options are agent (http.Agent()) and tls related options ('agent', 'ca', 'cert', 'ciphers', 'clientCertEngine', 'crl', 'dhparam', 'ecdhCurve', 'honorCipherOrder', 'key', 'passphrase', 'pfx', 'rejectUnauthorized', 'secureOptions', 'secureProtocol', 'servername', 'sessionIdContext') documented here
> 
> Copy
> // Do not reject self signed certificates.
> minioClient.setRequestOptions({rejectUnauthorized: false})

**Comment by AlloVince** [comment] 2018-10-07 11:11
Hi @harshavardhana 

I didn't get your point, according to [node.js document](https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback), to set a http request timeout, should use listener on request object, `http.request()` indeed has a `timeout` param, but it is the socket connect timeout, not the data transfer timeout.  so `setRequestOptions` not the correct way, please confirm.

> @AlloVince can you not do
> 
> https://docs.minio.io/docs/javascript-client-api-reference.html
> 
> > 1. HTTP request options
> >    setRequestOptions(options)
> >    Set the HTTP/HTTPS request options. Supported options are agent (http.Agent()) and tls related options ('agent', 'ca', 'cert', 'ciphers', 'clientCertEngine', 'crl', 'dhparam', 'ecdhCurve', 'honorCipherOrder', 'key', 'passphrase', 'pfx', 'rejectUnauthorized', 'secureOptions', 'secureProtocol', 'servername', 'sessionIdContext') documented here
> > 
> > Copy
> > // Do not reject self signed certificates.
> > minioClient.setRequestOptions({rejectUnauthorized: false})

**Comment by deekoder** [comment] 2018-11-01 23:07
@AlloVince. the server will send the calling clients this time out error. If you want client side timeout, i think this can be done by the calling application. Let me know your thought.

**Comment by AlloVince** [comment] 2018-11-02 03:16
@deekoder currently I has to write a child class of minio.Client and override the `makeRequestStream` to fix this. such as

``` js
class MyClient extends minio.Client {
      makeRequestStream(options, stream, sha256sum, statusCode, region, returnResponse, cb) {
           ... some original codes
           var _makeRequest = (e, region) => {
              ...
              var req = this.transport.request()
              ....
           }
           req.setTimeout(options.timeout || 5000, () => {
                req.abort()
          })
      }
}
```

Also here is full code https://github.com/AlloVince/yinxing.js/blob/master/src/services/minio.js#L92

But this way is just a temporary patch and ugly.

I think a better way is allow to set a global timeout for minio.Client such as:

``` js
var minioClient = new Minio.Client({
    endPoint: 'play.minio.io',
    timeout: 5000
});
```

Also each http request should allow to change timeout will be best


> @AlloVince. the server will send the calling clients this time out error. If you want client side timeout, i think this can be done by the calling application. Let me know your thought.

**Comment by deekoder** [comment] 2019-01-29 00:09
@AlloVince - This is not a standard s3 API requirement. I will check internally to make sure.

**Comment by AlloVince** [comment] 2019-01-29 02:18
> @AlloVince - This is not a standard s3 API requirement. I will check internally to make sure.

I think this is not a feature but an issue,  and may cause fatal problems.

I found this issue because one day all my scripts hang up without error log or crash, it is really hard to debug. So even not change the API parameter, I think at least should add a default global timeout for every http request, to make sure the process could work when network not stable.

**Comment by deekoder** [comment] 2019-03-05 00:30
@AlloVince  I will close this issue as working as intended. We try to keep our APIs similar to S3 APIs and allow applications to do whatever makes sense on their end. So please do feel free to reopen this thread if you want to discuss further.

**Closed** 2019-04-05 17:39 UTC
Labels: priority: medium, working as intended

**Comment by bell8910** [comment] 2023-06-16 09:34
@AlloVince AlloVince  thanks , your idea helps, i made some change that no need to modify minio client code.
 

`import * as Minio from 'minio'
import * as http from 'node:http'
import * as https from 'node:https'
import { RequestOptions, IncomingMessage, ClientRequest } from 'node:http';
   
   const request = (options: RequestOptions | string | URL, callback?: (res: IncomingMessage) => void): ClientRequest =>
    {
        (options as any).timeout = 5000;
        return useSSL?https.request(options,callback) : http.request(options, callback);
    }

    this.minioClient = new Minio.Client({
      endPoint: endpoint,
      port: port,
      useSSL: true,
      accessKey: accessKey,
      secretKey: secretKey,
      transport : { request }
      } as Minio.ClientOptions);
  }`
