### ISSUE TITLE
Install error in ubuntu 14.04

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-js#388] opened 2015-12-16 09:38 UTC
I am trying to install minio-js following https://github.com/minio/minio-js/blob/master/CONTRIBUTING.md on ubuntu 12.04
These are the steps i followed for installing package on ubuntu:
```
$ sudo apt-get install nodejs npm
```
To install minio-js package
```
$ sudo npm install
$ sudo npm install --global gulp
```
I am getting this error:

```
usr/bin/env: node: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

```

**Comment by harshavardhana** [comment] 2015-12-22 07:22
Did we document this?

**Comment by koolhead17** [comment] 2016-01-20 06:22
nope. Lets take this on tomorrows call & we can take it from there.

**Comment by harshavardhana** [comment] 2016-02-16 04:35
> nope. Lets take this on tomorrows call & we can take it from there.

Closing this not a bug.

**Closed by harshavardhana** 2016-02-16 04:35 UTC
Labels: future, question
