### ISSUE TITLE
fgetobject(): When is the file deleted ?

### ISSUE THREAD

**Issue by karthikSirsikar** [minio/minio-js#681] opened 2018-04-02 10:10 UTC
How and when is the file which is stored in local file system, got from fgetobject() deleted ? Is it deleted automatically ?

**Comment by ebozduman** [comment] 2018-04-02 21:17
@karthikSirsikar,

Could you please clarify the problem more?

Did you bring/get a file using `fGetObject()` minio-js api into your local filesystem and then the file disappeared/deleted without any good reason?

I just tried it and the file I brought/got, using minio-js `fGetObject(bucketName, objectName, filePath[, callback])`, sits intact in my local filesystem. 

We need to know more about the nature of the problem and the reproduction steps to be able to address it.
Thanks for your help.

**Comment by ebozduman** [comment] 2018-04-10 23:31
I am closing this issue for the time-being, since we could not reproduce it.
@karthikSirsikar, please feel free to re-open it if you see it again or if you can provide clear reproduction steps.

**Closed by ebozduman** 2018-04-10 23:31 UTC
Labels: priority: medium, triage

**Comment by karthikSirsikar** [comment] 2018-04-11 08:12
Thank you. It works fine. That was my mistake, I was saving the file in 'x' path and was trying to find it in 'y' path in filesystem.
