### ISSUE TITLE
support for url minio endpoints

### ISSUE THREAD

**Issue by mengu** [minio/minio-js#737] opened 2018-12-26 12:47 UTC
hi all

our minio instance does not live under its own hostname but under a url, such as https://domain.tld/minio/. when i want to use this library, it checks if the endpoint is a domain, rather than a valid url (https://github.com/minio/minio-js/blob/a180e877c6f887bd5b59ea02d0ec14cd537f1fe4/src/main/helpers.js#L112) hence my config becomes invalid. 

is there a specific reason for this? are you up for a PR fixing this?

thanks in advance.

**Comment by nitisht** [comment] 2018-12-26 12:50
We'll take a look @mengu

**Comment by mengu** [comment] 2018-12-26 16:12
thanks @nitisht. i'm looking forward to it.

**Comment by kanagarajkm** [comment] 2018-12-31 08:05
@mengu Minio works with the root of the domain. Its not possible to use a subdirectory with AWS3 signature.

Related issue https://github.com/minio/minio/issues/5947

**Comment by harshavardhana** [comment] 2018-12-31 09:52
We shouldn't be fixing this,  this is not a use case we are interested in addressing and it won't work due to AWS Signature security requirements.  Let's close this issue.

**Comment by harshavardhana** [comment] 2018-12-31 18:12
> it might not be a use case you are interested in but we use your library (and loving it!) and user experience begs to differ. :)
> 
> i'm not asking you to break aws signature security requirements but loosen up your validation. this is sort of path style aws uses.
> 
> in any case, i'm also ok with forking the lib.

The problem is providing many ways to do the same thing @mengu it makes it harder for us to document and communicate the intention of the API. We also don't want to make undocumented changes as well.

**Closed** 2019-01-03 12:06 UTC
Labels: community, priority: medium, wontfix

**Comment by gebv** [comment] 2020-05-20 20:54
@mengu If it's still relevant, few solutions for us
* reverse proxy via nginx - rewrite prefix and added option `proxy_set_header Host '127.0.0.1:9000'`
* use traefik with stripPrefix and sets static header Host

**Comment by manuFL** [comment] 2021-03-29 13:22
@gebv Hi gebv, I've got the first point, could you kindly explain me the second? I'm using traefik with k8s.

Thank you in advance
